name: CI Build

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 8
        uses: xt0rted/setup-dotnet@6f04e7f8ca9ff2faf76540fe2e3ebc595ca38b6b
        with:
          dotnet-version: 8.0.x
          include-prerelease: true

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/V2ex.Maui/V2ex.Maui.csproj

      - name: Build MAUI Android
        run: dotnet publish src/V2ex.Maui/V2ex.Maui.csproj -c Release -f net8.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: V2ex.Maui-android-ci-build
          path: src/V2ex.Maui/bin/Release/net8.0-android/*Signed.a*

# MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 8
        uses: xt0rted/setup-dotnet@6f04e7f8ca9ff2faf76540fe2e3ebc595ca38b6b
        with:
          dotnet-version: 8.0.x
          include-prerelease: true

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/V2ex.Maui/V2ex.Maui.csproj -r win10-x64

      - name: Build MAUI Windows
        run: dotnet publish src/V2ex.Maui/V2ex.Maui.csproj -c Release -f net8.0-windows10.0.19041.0 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: V2ex.Maui-windows-ci-build
          path: src/V2ex.Maui/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/V2ex.Maui*/V2ex.Maui*.msix

# # MAUI iOS Build
#   build-ios:
#     runs-on: macos-12
#     name: iOS Build
#     steps:

#       - name: Checkout
#         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

#       - name: Setup .NET 8
#         uses: xt0rted/setup-dotnet@6f04e7f8ca9ff2faf76540fe2e3ebc595ca38b6b
#         with:
#           dotnet-version: 8.0.x
#           include-prerelease: true

#       - name: Install MAUI Workload
#         run: dotnet workload install maui --ignore-failed-sources

#       - name: Restore Dependencies
#         run: dotnet restore src/V2ex.Maui/V2ex.Maui.csproj

#       - name: Build MAUI iOS
#         run: dotnet build src/V2ex.Maui/V2ex.Maui.csproj -c Release -f net8.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

#       - name: Upload iOS Artifact
#         uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
#         with:
#           name: V2ex.Maui-ios-ci-build
#           path: src/V2ex.Maui/bin/Release/net8.0-ios/iossimulator-x64/**/*.app

# # MAUI MacCatalyst Build
#   build-mac:
#     runs-on: macos-12
#     name: MacCatalyst Build
#     steps:

#       - name: Checkout
#         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

#       - name: Setup .NET 8
#         uses: xt0rted/setup-dotnet@6f04e7f8ca9ff2faf76540fe2e3ebc595ca38b6b
#         with:
#           dotnet-version: 8.0.x
#           include-prerelease: true

#       - name: Install MAUI Workload
#         run: dotnet workload install maui --ignore-failed-sources

#       - name: Restore Dependencies
#         run: dotnet restore src/V2ex.Maui/V2ex.Maui.csproj

#       - name: Build MAUI MacCatalyst
#         run: dotnet publish src/V2ex.Maui/V2ex.Maui.csproj -c Release -f net8.0-maccatalyst --no-restore -p:BuildIpa=True

#       - name: Upload MacCatalyst Artifact
#         uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
#         with:
#           name: V2ex.Maui-macos-ci-build
#           path: src/V2ex.Maui/bin/Release/net8.0-maccatalyst/maccatalyst-x64/publish/*.pkg
