name: PUBLISH Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: ubuntu-22.04
    name: Android Build
    steps:

        # Store the version, stripping any v-prefix
      - name: Write release version
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo Version: $TAG
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 8
        uses: xt0rted/setup-dotnet@6f04e7f8ca9ff2faf76540fe2e3ebc595ca38b6b
        with:
          dotnet-version: 8.0.x
          include-prerelease: true

      - name: Install MAUI Workload
        run: |
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/V2ex.Maui/V2ex.Maui.csproj

      - name: Build MAUI Android
        run: dotnet publish src/V2ex.Maui/V2ex.Maui.csproj -c Release -f net8.0-android --no-restore -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=v2ex.maui.keystore -p:AndroidSigningKeyAlias=v2ex.maui -p:AndroidSigningKeyPass=${{ secrets.KEY_STORE_PASSWORD }} -p:AndroidSigningStorePass=${{ secrets.KEY_PASSWORD }} -p:ApplicationDisplayVersion=${VERSION} -p:ApplicationVersion=${VERSION}

      - name: Upload Android Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: V2ex.Maui-android-build
          path: src/V2ex.Maui/bin/Release/net8.0-android/*Signed.a*
